begin;
select plan(18);
select ok(not has_function_privilege('authenticated', 'public.record_job_audio_check(uuid,double precision)', 'execute'), 'istemci preflight yazamaz');
select ok(not has_function_privilege('anon', 'public.apply_provider_callback(text,uuid,text,text,text,text,jsonb,text)', 'execute'), 'anon callback RPC çalıştıramaz');
select ok(not has_function_privilege('authenticated', 'public.tick_dispatcher()', 'execute'), 'istemci dispatcher tetikleyemez');
select is((select schedule from cron.job where jobname = 'dispatch-transcriptions'), '* * * * *', 'dispatcher dakikada bir');
select is(public.tick_dispatcher(), null::bigint, 'Vault boşken güvenli no-op');
insert into auth.users(id) values ('00000000-0000-0000-0000-0000000000e1');
insert into public.provider_prices(provider,model,price_version,usd_micros_per_minute,valid_from)
values ('fake','fake-v1','dispatcher-test',0,now() - interval '1 minute');
select public.grant_quota('00000000-0000-0000-0000-0000000000e1',60,now() - interval '1 minute',now() + interval '1 day','manual','dispatch-test');
create temp table d (id uuid, token text);
insert into d(id) select (public.create_transcription_job('00000000-0000-0000-0000-0000000000e1','dispatch-0001','tr',repeat('a',64),1000,1,'fake','fake-v1')).id;
select public.mark_job_uploaded('00000000-0000-0000-0000-0000000000e1',(select id from d));
select throws_ok(format('select public.record_job_audio_check(%L,60)',(select id from d)), 'P0001', 'audio_duration_mismatch', '60 sn ses 1 sn beyanla kabul edilmez');
select public.record_job_audio_check((select id from d),1);
select is((select inspected_duration_seconds from public.jobs where id = (select id from d)),1::float8,'ölçülen süre sunucuda tutulur');
select is((select count(*)::int from public.recover_fake_callback((select id from d))),0,'gönderilmemiş fake iş toparlama token alamaz');
update d set token = (select callback_token from public.claim_job_for_submission(d.id));
select public.mark_job_submitted((select id from d),'fake:dispatch-test');
select is(public.verify_job_callback((select id from d),repeat('b',64)),false,'yanlış token reddedilir');
create temp table old_token as select token from d;
update d set token = (select callback_token from public.recover_fake_callback(d.id));
select is(public.verify_job_callback((select id from d),(select token from old_token)),false,'toparlama eski fake tokenı geçersiz kılar');
select throws_ok(format($q$select public.apply_provider_callback('fake',%L,%L,'wrong','evt-1','succeeded','{"durationSeconds":1}')$q$,(select id from d),(select token from d)), 'P0002','job_not_found','başka provider request id reddedilir');
select is((public.apply_provider_callback('fake',(select id from d),(select token from d),'fake:dispatch-test','evt-1','succeeded','{"durationSeconds":1}')).status,'succeeded','callback işi tamamlar');
select is((public.apply_provider_callback('fake',(select id from d),(select token from d),'fake:dispatch-test','evt-1','succeeded','{"durationSeconds":1}')).status,'succeeded','aynı callback idempotent');
select is((select count(*)::int from public.usage_ledger where job_id = (select id from d)),1,'tek kota defter satırı');
select is((select sum(seconds)::int from public.usage_ledger where job_id = (select id from d)),1,'kota bir kez düşer');
select is((select count(*)::int from public.recover_fake_callback((select id from d))),0,'tamamlanmış işin tokenı değişmez');
set local role authenticated;
select throws_ok('select inspected_duration_seconds from public.jobs','42501',null,'istemci sunucu preflight alanını okuyamaz');
reset role;
select is((select count(*)::int from public.provider_events where job_id = (select id from d) and kind = 'webhook'),1,'tek callback olay satırı');
select * from finish();
rollback;
